"""Add completed column to todos table

Revision ID: 4b8bfb9f17d4
Revises: 54f05454ce4c
Create Date: 2025-02-21 23:33:04.334945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8bfb9f17d4'
down_revision: Union[str, None] = '54f05454ce4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('name', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'name')
    # ### end Alembic commands ###
